project_id = "cckrlamzicwryaqvvapt"

[functions.create-admin-user]
verify_jwt = false

[functions.ai-search]
verify_jwt = false

[functions.web-scrape-schools]
verify_jwt = false

[functions.ai-enrich-school]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false